### PR TITLE
Deprecate the anonymize filter

### PR DESCRIPTION
**Pull request by dedemorton**
@acchen97 Added the deprecated tag.

### CODE REVIEW

**Comment by dedemorton** [comment]
This PR closes https://github.com/logstash-plugins/logstash-filter-anonymize/issues/12

**Comment by acchen97** [comment]
@dedemorton LGTM. How far back should we backport this? We currently support back to Logstash 2.0.

**Comment by dedemorton** [comment]
@acchen97 That's a good question. I'm a bit concerned about backporting the deprecation statement because the documentation is supposed to reflect the version of the plugin that was bundled with Logstash when it shipped. Rather than backporting the deprecation statement, I could add a line to the docs for other versions to point to the fingerprint filter plugin as a better alternative. I think the deprecation statement really only belongs in the latest version of the doc. WDYT?

**Comment by acchen97** [comment]
@dedemorton solid suggestion, sounds good to me. Thanks! :)

**Comment by dedemorton** [comment]
Note that I've added notes to the anonymize filter docs from 2.0 -> 5.x to indicate that the fingerprint filter is recommended. See https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Adedemorton+is%3Aclosed+Add+note+to+use+fingerprint

**Comment by acchen97** [comment]
Awesome thank you!

**Pull request merged**
